-- Consolidated Migration File generated by Gemini
-- Generated at: 2026-05-28T11:00:00Z

--
-- From: 20260521T120000_build_phase2_core_schema.sql
--

create schema if not exists app;
create schema if not exists indexer;

create extension if not exists pgcrypto;

do $$
begin
  if not exists (select 1 from pg_type where typname = 'app_role') then
    create type app.app_role as enum ('voter', 'admin', 'super_admin');
  end if;

  if not exists (select 1 from pg_type where typname = 'proposal_status') then
    create type app.proposal_status as enum ('draft', 'submitted', 'revision_requested', 'approved', 'rejected', 'deployed', 'archived');
  end if;

  if not exists (select 1 from pg_type where typname = 'whitelist_source') then
    create type app.whitelist_source as enum ('manual', 'csv', 'sync');
  end if;

  if not exists (select 1 from pg_type where typname = 'validation_status') then
    create type app.validation_status as enum ('pending', 'valid', 'invalid', 'synced', 'failed');
  end if;

  if not exists (select 1 from pg_type where typname = 'tx_action_type') then
    create type app.tx_action_type as enum (
      'submit_proposal',
      'review_proposal',
      'deploy_space',
      'register_voter',
      'unregister_voter',
      'phase_transition',
      'commit_vote',
      'reveal_vote',
      'suspend_space',
      'unsuspend_space',
      'terminate_space'
    );
  end if;

  if not exists (select 1 from pg_type where typname = 'proof_type') then
    create type app.proof_type as enum ('commit_receipt', 'reveal_receipt', 'space_report', 'audit_bundle');
  end if;

  if not exists (select 1 from pg_type where typname = 'notification_channel') then
    create type app.notification_channel as enum ('in_app', 'email', 'webhook');
  end if;

  if not exists (select 1 from pg_type where typname = 'notification_status') then
    create type app.notification_status as enum ('queued', 'sent', 'failed', 'cancelled');
  end if;

  if not exists (select 1 from pg_type where typname = 'sync_health_status') then
    create type indexer.sync_health_status as enum ('ok', 'lagging', 'resyncing', 'degraded');
  end if;
end $$;

create or replace function app.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

create table if not exists app.app_profiles (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null unique references auth.users(id) on delete cascade,
  wallet_address text not null unique,
  display_name text,
  email text unique,
  role app.app_role not null default 'voter',
  role_hint text,
  avatar_url text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint wallet_address_format check (wallet_address ~ '^0x[a-fA-F0-9]{40}$')
);

create table if not exists app.proposal_drafts (
  id uuid primary key default gen_random_uuid(),
  created_by uuid not null references app.app_profiles(id) on delete restrict,
  title text not null,
  description text,
  organization_name text,
  theme_color text not null default '#0F172A',
  rules_text text,
  candidate_count integer not null default 0,
  status app.proposal_status not null default 'draft',
  metadata_version integer not null default 1,
  onchain_proposal_id bigint,
  proposal_tx_hash text,
  review_tx_hash text,
  deployment_tx_hash text,
  deployed_space_id bigint,
  deployed_space_address text,
  commit_start_at timestamptz,
  reveal_start_at timestamptz,
  ended_at timestamptz,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint theme_color_hex check (theme_color ~ '^#[A-Fa-f0-9]{6}$'),
  constraint proposal_tx_hash_hex check (proposal_tx_hash is null or proposal_tx_hash ~ '^0x[a-fA-F0-9]{64}$'),
  constraint review_tx_hash_hex check (review_tx_hash is null or review_tx_hash ~ '^0x[a-fA-F0-9]{64}$'),
  constraint deployment_tx_hash_hex check (deployment_tx_hash is null or deployment_tx_hash ~ '^0x[a-fA-F0-9]{64}$'),
  constraint deployed_space_address_hex check (deployed_space_address is null or deployed_space_address ~ '^0x[a-fA-F0-9]{40}$')
);

create table if not exists app.proposal_candidates (
  id uuid primary key default gen_random_uuid(),
  proposal_draft_id uuid not null references app.proposal_drafts(id) on delete cascade,
  candidate_local_id text not null,
  full_name text not null,
  student_id text,
  faculty text,
  bio text,
  vision text,
  mission jsonb not null default '[]'::jsonb,
  youtube_url text,
  avatar_path text,
  sort_order integer not null default 0,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (proposal_draft_id, candidate_local_id)
);

create table if not exists app.whitelist_import_jobs (
  id uuid primary key default gen_random_uuid(),
  proposal_draft_id uuid not null references app.proposal_drafts(id) on delete cascade,
  created_by uuid not null references app.app_profiles(id) on delete restrict,
  file_path text not null,
  file_name text not null,
  row_count integer not null default 0,
  invalid_count integer not null default 0,
  status app.validation_status not null default 'pending',
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists app.proposal_documents (
  id uuid primary key default gen_random_uuid(),
  proposal_draft_id uuid not null references app.proposal_drafts(id) on delete cascade,
  uploaded_by uuid not null references app.app_profiles(id) on delete restrict,
  file_path text not null,
  file_name text not null,
  content_type text not null default 'application/pdf',
  file_size bigint not null default 0,
  document_type text not null default 'supporting',
  created_at timestamptz not null default timezone('utc', now()),
  constraint proposal_documents_type_check check (document_type in ('supporting', 'recommendation_letter')),
  constraint proposal_documents_pdf_check check (content_type = 'application/pdf')
);

create index if not exists idx_proposal_documents_proposal_draft_id
on app.proposal_documents(proposal_draft_id, created_at desc);

create table if not exists app.proposal_whitelist_entries (
  id uuid primary key default gen_random_uuid(),
  proposal_draft_id uuid not null references app.proposal_drafts(id) on delete cascade,
  import_job_id uuid references app.whitelist_import_jobs(id) on delete set null,
  wallet_address text not null,
  voter_name text,
  source app.whitelist_source not null default 'manual',
  validation_status app.validation_status not null default 'pending',
  sync_status app.validation_status not null default 'pending',
  latest_sync_tx_hash text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint whitelist_wallet_format check (wallet_address ~ '^0x[a-fA-F0-9]{40}$'),
  constraint whitelist_sync_tx_hash_hex check (latest_sync_tx_hash is null or latest_sync_tx_hash ~ '^0x[a-fA-F0-9]{64}$'),
  unique (proposal_draft_id, wallet_address)
);

create table if not exists app.space_metadata_versions (
  id uuid primary key default gen_random_uuid(),
  proposal_draft_id uuid not null references app.proposal_drafts(id) on delete cascade,
  version integer not null,
  metadata_uri text not null,
  content_hash text not null,
  is_final boolean not null default false,
  created_by uuid references app.app_profiles(id) on delete set null,
  created_at timestamptz not null default timezone('utc', now()),
  unique (proposal_draft_id, version),
  constraint content_hash_hex check (content_hash ~ '^0x[a-fA-F0-9]{64}$')
);

create table if not exists app.space_registry_map (
  id uuid primary key default gen_random_uuid(),
  proposal_draft_id uuid unique references app.proposal_drafts(id) on delete cascade,
  chain_id bigint not null default 84532,
  onchain_proposal_id bigint,
  space_id bigint,
  registry_address text not null,
  space_address text,
  owner_wallet text not null,
  deployment_tx_hash text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint registry_address_hex check (registry_address ~ '^0x[a-fA-F0-9]{40}$'),
  constraint space_address_hex check (space_address is null or space_address ~ '^0x[a-fA-F0-9]{40}$'),
  constraint owner_wallet_hex check (owner_wallet ~ '^0x[a-fA-F0-9]{40}$'),
  constraint deployment_tx_hash_hex_map check (deployment_tx_hash is null or deployment_tx_hash ~ '^0x[a-fA-F0-9]{64}$')
);

create table if not exists app.tx_audit_log (
  id uuid primary key default gen_random_uuid(),
  space_id bigint,
  proposal_draft_id uuid references app.proposal_drafts(id) on delete set null,
  wallet_address text not null,
  action_type app.tx_action_type not null,
  tx_hash text not null,
  block_number bigint,
  status text not null default 'pending',
  source text not null default 'frontend',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (tx_hash, action_type),
  constraint tx_audit_wallet_hex check (wallet_address ~ '^0x[a-fA-F0-9]{40}$'),
  constraint tx_audit_hash_hex check (tx_hash ~ '^0x[a-fA-F0-9]{64}$')
);

create table if not exists app.proof_exports (
  id uuid primary key default gen_random_uuid(),
  space_id bigint,
  owner_profile_id uuid references app.app_profiles(id) on delete set null,
  wallet_address text not null,
  proof_type app.proof_type not null,
  file_path text not null,
  tx_hash text,
  generated_at timestamptz not null default timezone('utc', now()),
  metadata jsonb not null default '{}'::jsonb,
  constraint proof_wallet_hex check (wallet_address ~ '^0x[a-fA-F0-9]{40}$'),
  constraint proof_tx_hash_hex check (tx_hash is null or tx_hash ~ '^0x[a-fA-F0-9]{64}$')
);

create table if not exists app.ops_audit_log (
  id uuid primary key default gen_random_uuid(),
  actor_profile_id uuid references app.app_profiles(id) on delete set null,
  actor_wallet text,
  action_name text not null,
  entity_type text not null,
  entity_id text not null,
  request_id text,
  before_state jsonb,
  after_state jsonb,
  related_tx_hash text,
  created_at timestamptz not null default timezone('utc', now()),
  constraint ops_audit_wallet_hex check (actor_wallet is null or actor_wallet ~ '^0x[a-fA-F0-9]{40}$'),
  constraint ops_audit_tx_hex check (related_tx_hash is null or related_tx_hash ~ '^0x[a-fA-F0-9]{64}$')
);

create table if not exists app.notification_jobs (
  id uuid primary key default gen_random_uuid(),
  space_id bigint,
  target_profile_id uuid references app.app_profiles(id) on delete set null,
  target_wallet text,
  channel app.notification_channel not null,
  template_key text not null,
  status app.notification_status not null default 'queued',
  payload jsonb not null default '{}'::jsonb,
  sent_at timestamptz,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint notification_wallet_hex check (target_wallet is null or target_wallet ~ '^0x[a-fA-F0-9]{40}$')
);

create table if not exists indexer.indexer_sync_status (
  id uuid primary key default gen_random_uuid(),
  chain_id bigint not null default 84532,
  source_key text not null unique,
  latest_indexed_block bigint,
  latest_indexed_block_time timestamptz,
  latest_safe_block bigint,
  head_lag_blocks integer,
  head_lag_seconds integer,
  health_status indexer.sync_health_status not null default 'degraded',
  last_error_message text,
  last_error_at timestamptz,
  last_reorg_at timestamptz,
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_app_profiles_wallet on app.app_profiles(wallet_address);
create index if not exists idx_proposal_drafts_created_by on app.proposal_drafts(created_by, status);
create index if not exists idx_proposal_candidates_proposal on app.proposal_candidates(proposal_draft_id, sort_order);
create index if not exists idx_whitelist_entries_proposal on app.proposal_whitelist_entries(proposal_draft_id, sync_status);
create index if not exists idx_space_registry_map_space on app.space_registry_map(space_id);
create index if not exists idx_tx_audit_log_space on app.tx_audit_log(space_id, created_at desc);
create index if not exists idx_tx_audit_log_wallet on app.tx_audit_log(wallet_address, created_at desc);
create index if not exists idx_proof_exports_owner on app.proof_exports(owner_profile_id, generated_at desc);
create index if not exists idx_ops_audit_actor on app.ops_audit_log(actor_profile_id, created_at desc);
create index if not exists idx_notification_jobs_status on app.notification_jobs(status, created_at asc);

create trigger set_app_profiles_updated_at
before update on app.app_profiles
for each row execute function app.set_updated_at();

create trigger set_proposal_drafts_updated_at
before update on app.proposal_drafts
for each row execute function app.set_updated_at();

create trigger set_proposal_candidates_updated_at
before update on app.proposal_candidates
for each row execute function app.set_updated_at();

create trigger set_whitelist_import_jobs_updated_at
before update on app.whitelist_import_jobs
for each row execute function app.set_updated_at();

create trigger set_proposal_whitelist_entries_updated_at
before update on app.proposal_whitelist_entries
for each row execute function app.set_updated_at();

create trigger set_space_registry_map_updated_at
before update on app.space_registry_map
for each row execute function app.set_updated_at();

create trigger set_tx_audit_log_updated_at
before update on app.tx_audit_log
for each row execute function app.set_updated_at();

create trigger set_notification_jobs_updated_at
before update on app.notification_jobs
for each row execute function app.set_updated_at();

create trigger set_indexer_sync_status_updated_at
before update on indexer.indexer_sync_status
for each row execute function app.set_updated_at();

create or replace function app.current_profile_id()
returns uuid
language sql
stable
security definer
set search_path = app
as $$
  select id from app.app_profiles where user_id = auth.uid() limit 1;
$$;

create or replace function app.current_user_role()
returns app.app_role
language sql
stable
security definer
set search_path = app
as $$
  select role from app.app_profiles where user_id = auth.uid() limit 1;
$$;

create or replace function app.has_role(roles app.app_role[])
returns boolean
language sql
stable
security definer
set search_path = app
as $$
  select exists (
    select 1
    from app.app_profiles
    where user_id = auth.uid()
      and role = any(roles)
  );
$$;

alter table app.app_profiles enable row level security;
alter table app.proposal_drafts enable row level security;
alter table app.proposal_candidates enable row level security;
alter table app.whitelist_import_jobs enable row level security;
alter table app.proposal_documents enable row level security;
alter table app.proposal_whitelist_entries enable row level security;
alter table app.space_metadata_versions enable row level security;
alter table app.space_registry_map enable row level security;
alter table app.tx_audit_log enable row level security;
alter table app.proof_exports enable row level security;
alter table app.ops_audit_log enable row level security;
alter table app.notification_jobs enable row level security;
alter table indexer.indexer_sync_status enable row level security;

create policy "profiles_select_self_or_admin"
on app.app_profiles
for select
using (user_id = auth.uid() or app.has_role(array['admin'::app.app_role, 'super_admin'::app.app_role]));

create policy "profiles_insert_self"
on app.app_profiles
for insert
with check (user_id = auth.uid());

create policy "profiles_update_self_or_admin"
on app.app_profiles
for update
using (user_id = auth.uid() or app.has_role(array['admin'::app.app_role, 'super_admin'::app.app_role]))
with check (user_id = auth.uid() or app.has_role(array['admin'::app.app_role, 'super_admin'::app.app_role]));

create policy "proposal_drafts_select_owner_or_admin"
on app.proposal_drafts
for select
using (
  created_by = app.current_profile_id()
  or app.has_role(array['admin'::app.app_role, 'super_admin'::app.app_role])
);

create policy "proposal_drafts_insert_admin"
on app.proposal_drafts
for insert
with check (
  created_by = app.current_profile_id()
  and app.has_role(array['admin'::app.app_role, 'super_admin'::app.app_role])
);

create policy "proposal_drafts_update_owner_or_admin"
on app.proposal_drafts
for update
using (
  created_by = app.current_profile_id()
  or app.has_role(array['admin'::app.app_role, 'super_admin'::app.app_role])
)
with check (
  created_by = app.current_profile_id()
  or app.has_role(array['admin'::app.app_role, 'super_admin'::app.app_role])
);

create policy "proposal_candidates_manage_parent_owner_or_admin"
on app.proposal_candidates
for all
using (
  exists (
    select 1
    from app.proposal_drafts d
    where d.id = proposal_draft_id
      and (
        d.created_by = app.current_profile_id()
        or app.has_role(array['admin'::app.app_role, 'super_admin'::app.app_role])
      )
  )
)
with check (
  exists (
    select 1
    from app.proposal_drafts d
    where d.id = proposal_draft_id
      and (
        d.created_by = app.current_profile_id()
        or app.has_role(array['admin'::app.app_role, 'super_admin'::app.app_role])
      )
  )
);

create policy "whitelist_jobs_manage_parent_owner_or_admin"
on app.whitelist_import_jobs
for all
using (
  exists (
    select 1
    from app.proposal_drafts d
    where d.id = proposal_draft_id
      and (
        d.created_by = app.current_profile_id()
        or app.has_role(array['admin'::app.app_role, 'super_admin'::app.app_role])
      )
  )
)
with check (
  created_by = app.current_profile_id()
  and exists (
    select 1
    from app.proposal_drafts d
    where d.id = proposal_draft_id
      and (
        d.created_by = app.current_profile_id()
        or app.has_role(array['admin'::app.app_role, 'super_admin'::app.app_role])
      )
  )
);

create policy "whitelist_entries_manage_parent_owner_or_admin"
on app.proposal_whitelist_entries
for all
using (
  exists (
    select 1
    from app.proposal_drafts d
    where d.id = proposal_draft_id
      and (
        d.created_by = app.current_profile_id()
        or app.has_role(array['admin'::app.app_role, 'super_admin'::app.app_role])
      )
  )
)
with check (
  exists (
    select 1
    from app.proposal_drafts d
    where d.id = proposal_draft_id
      and (
        d.created_by = app.current_profile_id()
        or app.has_role(array['admin'::app.app_role, 'super_admin'::app.app_role])
      )
  )
);

create policy "metadata_versions_select_owner_or_admin"
on app.space_metadata_versions
for select
using (
  exists (
    select 1
    from app.proposal_drafts d
    where d.id = proposal_draft_id
      and (
        d.created_by = app.current_profile_id()
        or app.has_role(array['admin'::app.app_role, 'super_admin'::app.app_role])
      )
  )
);

create policy "metadata_versions_insert_admin"
on app.space_metadata_versions
for insert
with check (
  exists (
    select 1
    from app.proposal_drafts d
    where d.id = proposal_draft_id
      and (
        d.created_by = app.current_profile_id()
        or app.has_role(array['admin'::app.app_role, 'super_admin'::app.app_role])
      )
  )
);

create policy "space_registry_map_select_owner_or_admin"
on app.space_registry_map
for select
using (
  exists (
    select 1
    from app.proposal_drafts d
    where d.id = proposal_draft_id
      and (
        d.created_by = app.current_profile_id()
        or app.has_role(array['admin'::app.app_role, 'super_admin'::app.app_role])
      )
  )
);

create policy "space_registry_map_insert_superadmin"
on app.space_registry_map
for insert
with check (app.has_role(array['super_admin'::app.app_role]));

create policy "space_registry_map_update_superadmin"
on app.space_registry_map
for update
using (app.has_role(array['super_admin'::app.app_role]))
with check (app.has_role(array['super_admin'::app.app_role]));

create policy "tx_audit_log_select_owner_or_admin"
on app.tx_audit_log
for select
using (
  wallet_address in (
    select wallet_address from app.app_profiles where user_id = auth.uid()
  )
  or app.has_role(array['admin'::app.app_role, 'super_admin'::app.app_role])
);

create policy "tx_audit_log_insert_owner_or_admin"
on app.tx_audit_log
for insert
with check (
  wallet_address in (
    select wallet_address from app.app_profiles where user_id = auth.uid()
  )
  or app.has_role(array['admin'::app.app_role, 'super_admin'::app.app_role])
);

create policy "proof_exports_select_owner_or_admin"
on app.proof_exports
for select
using (
  owner_profile_id = app.current_profile_id()
  or app.has_role(array['admin'::app.app_role, 'super_admin'::app.app_role])
);

create policy "proof_exports_insert_owner_or_admin"
on app.proof_exports
for insert
with check (
  owner_profile_id = app.current_profile_id()
  or app.has_role(array['admin'::app.app_role, 'super_admin'::app.app_role])
);

create policy "ops_audit_log_select_admin_only"
on app.ops_audit_log
for select
using (app.has_role(array['admin'::app.app_role, 'super_admin'::app.app_role]));

create policy "notification_jobs_select_target_or_admin"
on app.notification_jobs
for select
using (
  target_profile_id = app.current_profile_id()
  or target_wallet in (select wallet_address from app.app_profiles where user_id = auth.uid())
  or app.has_role(array['admin'::app.app_role, 'super_admin'::app.app_role])
);

create policy "indexer_sync_status_select_authenticated"
on indexer.indexer_sync_status
for select
using (auth.role() = 'authenticated');

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values
  ('space-metadata', 'space-metadata', false, 52428800, array['application/json']),
  ('proof-exports', 'proof-exports', false, 52428800, array['application/json', 'application/pdf'])
on conflict (id) do nothing;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('proposal-documents', 'proposal-documents', false, 10485760, array['application/pdf'])
on conflict (id) do update
set public = excluded.public,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('public-assets', 'public-assets', true, 10485760, array['image/jpeg', 'image/png'])
on conflict (id) do update
set public = excluded.public,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

--
-- From: 20260527T090000_admin_registry_invites.sql
--

create schema if not exists app;

do $$
begin
  if not exists (select 1 from pg_type where typnamespace = 'app'::regnamespace and typname = 'app_role') then
    create type app.app_role as enum ('voter', 'admin', 'super_admin');
  end if;
end $$;

create or replace function app.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

create or replace function app.current_profile_id()
returns uuid
language sql
stable
security definer
set search_path = app
as $$
  select id from app.app_profiles where user_id = auth.uid() limit 1;
$$;

create or replace function app.has_role(roles app.app_role[])
returns boolean
language sql
stable
security definer
set search_path = app
as $$
  select exists (
    select 1
    from app.app_profiles
    where user_id = auth.uid()
      and role = any(roles)
  );
$$;

create table if not exists app.admin_registry (
  email text primary key,
  assigned_role app.app_role not null default 'admin',
  organization_name text,
  access_scope text not null default 'all',
  status text not null default 'pending',
  description text,
  created_by uuid references app.app_profiles(id) on delete set null,
  updated_by uuid references app.app_profiles(id) on delete set null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint admin_registry_email_format check (email ~* '^[^\s@]+@[^\s@]+\.[^\s@]+$'),
  constraint admin_registry_scope_check check (access_scope in ('all', 'specific')),
  constraint admin_registry_status_check check (status in ('pending', 'active', 'inactive')),
  constraint admin_registry_role_check check (assigned_role in ('voter'::app.app_role, 'admin'::app.app_role, 'super_admin'::app.app_role))
);


alter table app.admin_registry
  add column if not exists organization_name text,
  add column if not exists access_scope text not null default 'all',
  add column if not exists status text not null default 'pending',
  add column if not exists created_by uuid references app.app_profiles(id) on delete set null,
  add column if not exists updated_by uuid references app.app_profiles(id) on delete set null,
  add column if not exists updated_at timestamptz not null default timezone('utc', now());

update app.admin_registry
set access_scope = 'all'
where access_scope is null;

update app.admin_registry
set status = 'pending'
where status is null;

drop trigger if exists set_admin_registry_updated_at on app.admin_registry;
create trigger set_admin_registry_updated_at
before update on app.admin_registry
for each row execute function app.set_updated_at();

alter table app.admin_registry enable row level security;

create or replace function app.role_for_email(input_email text)
returns app.app_role
language sql
stable
security definer
set search_path = app
as $$
  select coalesce((
    select assigned_role
    from app.admin_registry
    where lower(email) = lower(coalesce(input_email, ''))
      and status = 'active'
      and assigned_role in ('voter'::app.app_role, 'admin'::app.app_role, 'super_admin'::app.app_role)
    limit 1

  ), 'voter'::app.app_role);
$$;

create or replace function app.auth_email()
returns text
language sql
stable
security definer
set search_path = app
as $$
  select lower(nullif(auth.jwt() ->> 'email', ''));
$$;

grant execute on function app.auth_email() to authenticated, service_role;

drop policy if exists "profiles_insert_self" on app.app_profiles;
drop policy if exists "profiles_update_self_or_admin" on app.app_profiles;
drop policy if exists "profiles_update_self_or_superadmin" on app.app_profiles;

create policy "profiles_insert_self"
on app.app_profiles
for insert
with check (
  user_id = auth.uid()
  and (email is null or lower(email) = app.auth_email())
  and role = app.role_for_email(app.auth_email())
);

create policy "profiles_update_self_or_superadmin"
on app.app_profiles
for update
using (
  user_id = auth.uid()
  or app.has_role(array['super_admin'::app.app_role])
)
with check (
  (
    user_id = auth.uid()
    and (email is null or lower(email) = app.auth_email())
    and (
      role = app.role_for_email(app.auth_email())
      or (app.current_user_role() = 'super_admin'::app.app_role and role = 'super_admin'::app.app_role)
    )
  )
  or app.has_role(array['super_admin'::app.app_role])
);

drop policy if exists "admin_registry_select_self_or_superadmin" on app.admin_registry;
drop policy if exists "admin_registry_insert_superadmin" on app.admin_registry;
drop policy if exists "admin_registry_update_superadmin" on app.admin_registry;
drop policy if exists "admin_registry_delete_superadmin" on app.admin_registry;

create policy "admin_registry_select_self_or_superadmin"
on app.admin_registry
for select
using (
  app.has_role(array['super_admin'::app.app_role])
  or lower(email) = lower(coalesce(auth.jwt() ->> 'email', ''))
);

create policy "admin_registry_insert_superadmin"
on app.admin_registry
for insert
with check (app.has_role(array['super_admin'::app.app_role]));

create policy "admin_registry_update_superadmin"
on app.admin_registry
for update
using (app.has_role(array['super_admin'::app.app_role]))
with check (app.has_role(array['super_admin'::app.app_role]));

create policy "admin_registry_delete_superadmin"
on app.admin_registry
for delete
using (app.has_role(array['super_admin'::app.app_role]));

--
-- From: 20260528T100000_risk_management.sql
--

-- Migration: Risk Management Schema
-- Description: Adds tables for risk alerts and blocked entities for superadmin monitoring.

do $$
begin
  if not exists (select 1 from pg_type where typname = 'risk_tone') then
    create type app.risk_tone as enum ('danger', 'warning', 'info');
  end if;

  if not exists (select 1 from pg_type where typname = 'risk_status') then
    create type app.risk_status as enum ('active', 'resolved', 'blocked');
  end if;
end $$;

create table if not exists app.risk_alerts (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  description text not null,
  actor_label text not null, -- e.g., 'IP Aktor', 'Wallet Address', 'ID Ruang'
  actor_value text not null,
  tone app.risk_tone not null default 'warning',
  status app.risk_status not null default 'active',
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists app.blocked_entities (
  id uuid primary key default gen_random_uuid(),
  entity_type text not null, -- 'ip', 'wallet', 'space'
  entity_value text not null,
  reason text,
  blocked_by uuid references app.app_profiles(id),
  created_at timestamptz not null default timezone('utc', now()),
  unique (entity_type, entity_value)
);

-- Enable RLS
alter table app.risk_alerts enable row level security;
alter table app.blocked_entities enable row level security;

-- Policies for Super Admin
create policy "super_admin_all_risk_alerts"
on app.risk_alerts
for all
using (app.has_role(array['super_admin'::app.app_role]))
with check (app.has_role(array['super_admin'::app.app_role]));

create policy "super_admin_all_blocked_entities"
on app.blocked_entities
for all
using (app.has_role(array['super_admin'::app.app_role]))
with check (app.has_role(array['super_admin'::app.app_role]));

-- Trigger for updated_at
create trigger set_risk_alerts_updated_at
before update on app.risk_alerts
for each row execute function app.set_updated_at();

-- Indexes
create index if not exists idx_risk_alerts_status on app.risk_alerts(status, created_at desc);
create index if not exists idx_blocked_entities_value on app.blocked_entities(entity_value);

--
-- From: 20260528T130000_admin_activation_tokens.sql
--

alter table app.admin_registry
  add column if not exists wallet_address text,
  add column if not exists activation_token_hash text,
  add column if not exists activation_sent_at timestamptz,
  add column if not exists activation_expires_at timestamptz,
  add column if not exists activation_accepted_at timestamptz;

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'admin_registry_wallet_format'
  ) then
    alter table app.admin_registry
      add constraint admin_registry_wallet_format
      check (wallet_address is null or wallet_address ~ '^0x[a-fA-F0-9]{40}$');
  end if;
end $$;

create unique index if not exists admin_registry_activation_token_hash_idx
on app.admin_registry (activation_token_hash)
where activation_token_hash is not null;

create or replace function app.role_for_email(input_email text)
returns app.app_role
language sql
stable
security definer
set search_path = app
as $$
  select coalesce((
    select assigned_role
    from app.admin_registry
    where lower(email) = lower(coalesce(input_email, ''))
      and (
        (assigned_role = 'voter'::app.app_role and status in ('pending', 'active'))
        or (assigned_role = 'admin'::app.app_role and status = 'active')
        or (assigned_role = 'super_admin'::app.app_role and status = 'active')
      )
      and assigned_role in ('voter'::app.app_role, 'admin'::app.app_role, 'super_admin'::app.app_role)
    limit 1

  ), 'voter'::app.app_role);
$$;

--
-- From: 20260528T140000_ensure_schema_permissions.sql
--

-- Migration: Ensure Schema Permissions
-- Description: Grants usage on 'app' schema to necessary roles.

grant usage on schema app to anon, authenticated, service_role;
grant usage on schema indexer to anon, authenticated, service_role;

grant all privileges on all tables in schema app to service_role;
grant all privileges on all sequences in schema app to service_role;
grant all privileges on all functions in schema app to service_role;

grant usage on all sequences in schema app to authenticated;
grant execute on all functions in schema app to authenticated;

grant usage on all sequences in schema app to anon;
grant execute on all functions in schema app to anon;

grant select, insert, update, delete on all tables in schema app to anon, authenticated;
grant usage, select on all sequences in schema app to anon, authenticated;
grant select on all tables in schema indexer to anon, authenticated;
grant usage, select on all sequences in schema indexer to anon, authenticated;

--
-- Consolidated follow-up migrations
-- Includes former 20260531000001_create_platform_settings.sql
-- and 20260531000002_activation_notification.sql
--

create table if not exists app.platform_settings (
    id uuid primary key default gen_random_uuid(),
    platform_name text not null default 'VoteIn e-Voting',
    default_language text not null default 'Bahasa Indonesia',
    network_name text not null default 'Base Sepolia',
    rpc_url text,
    registry_address text,
    gas_limit integer not null default 50,
    updated_at timestamptz default timezone('utc', now())
);

alter table app.platform_settings enable row level security;

drop policy if exists "platform_settings_select_all" on app.platform_settings;
create policy "platform_settings_select_all" on app.platform_settings
    for select using (true);

drop policy if exists "platform_settings_manage_superadmin" on app.platform_settings;
create policy "platform_settings_manage_superadmin" on app.platform_settings
    for all using (
        app.has_role(array['super_admin'::app.app_role])
    );

grant select, insert, update, delete on app.platform_settings to anon, authenticated;

drop trigger if exists set_platform_settings_updated_at on app.platform_settings;
create trigger set_platform_settings_updated_at
before update on app.platform_settings
for each row execute function app.set_updated_at();

insert into app.platform_settings (platform_name, default_language, network_name, gas_limit)
values ('VoteIn e-Voting', 'Bahasa Indonesia', 'Base Sepolia', 50)
on conflict do nothing;

create or replace function app.on_profile_activation_notify()
returns trigger as $$
begin
    insert into app.notification_jobs (
        target_profile_id,
        channel,
        template_key,
        payload
    ) values (
        new.id,
        'in_app',
        'ACCOUNT_ACTIVATED',
        jsonb_build_object(
            'title', 'Akun Berhasil Diaktifkan',
            'display_name', new.display_name,
            'email', new.email,
            'message', 'Akun Anda telah berhasil diaktifkan. Anda kini dapat berpartisipasi dalam ekosistem e-voting dan mengelola data pemilihan.'
        )
    );
    return new;
end;
$$ language plpgsql security definer;

drop trigger if exists on_profile_activated on app.app_profiles;
create trigger on_profile_activated
after insert on app.app_profiles
for each row
execute function app.on_profile_activation_notify();

-- -----------------------------------------------------------------------------
-- Admin Specific Access Control
-- -----------------------------------------------------------------------------

create table if not exists app.admin_space_access (
  id uuid primary key default gen_random_uuid(),
  admin_email text not null references app.admin_registry(email) on delete cascade,
  proposal_draft_id uuid not null references app.proposal_drafts(id) on delete cascade,
  created_at timestamptz not null default timezone('utc', now()),
  unique (admin_email, proposal_draft_id)
);

-- Enable RLS
alter table app.admin_space_access enable row level security;

-- Policies for Admin Space Access
drop policy if exists "super_admin_manage_all_access" on app.admin_space_access;
create policy "super_admin_manage_all_access"
on app.admin_space_access
for all
using (app.has_role(array['super_admin'::app.app_role]))
with check (app.has_role(array['super_admin'::app.app_role]));

drop policy if exists "admin_view_own_access" on app.admin_space_access;
create policy "admin_view_own_access"
on app.admin_space_access
for select
using (
  lower(admin_email) = lower(coalesce(auth.jwt() ->> 'email', ''))
);

-- Update Proposal Drafts RLS to be more restrictive for Admins with 'specific' scope
drop policy if exists "proposal_drafts_select_owner_or_admin" on app.proposal_drafts;
drop policy if exists "proposal_drafts_select_restricted" on app.proposal_drafts;
drop policy if exists "proposal_drafts_update_owner_or_admin" on app.proposal_drafts;
drop policy if exists "proposal_drafts_update_restricted" on app.proposal_drafts;

create policy "proposal_drafts_select_restricted"
on app.proposal_drafts
for select
using (
  -- Super Admin sees everything
  app.has_role(array['super_admin'::app.app_role])
  or (
    -- Admin restricted by scope
    app.has_role(array['admin'::app.app_role])
    and (
      -- Case 1: Admin has 'all' scope
      exists (
        select 1 from app.admin_registry
        where lower(email) = lower(coalesce(auth.jwt() ->> 'email', ''))
          and access_scope = 'all'
          and status != 'inactive'
      )
      -- Case 2: Admin is the owner (creator) of the proposal
      or created_by = app.current_profile_id()
      -- Case 3: Admin is specifically assigned to this proposal
      or exists (
        select 1 from app.admin_space_access
        where lower(admin_email) = lower(coalesce(auth.jwt() ->> 'email', ''))
          and proposal_draft_id = id
      )
    )
  )
);

create policy "proposal_drafts_update_restricted"
on app.proposal_drafts
for update
using (
  -- Super Admin may update every proposal draft.
  app.has_role(array['super_admin'::app.app_role])
  or (
    -- Admin follows the same scope restriction used by SELECT.
    app.has_role(array['admin'::app.app_role])
    and (
      created_by = app.current_profile_id()
      or exists (
        select 1 from app.admin_registry
        where lower(email) = app.auth_email()
          and access_scope = 'all'
          and status != 'inactive'
      )
      or exists (
        select 1 from app.admin_space_access
        where lower(admin_email) = app.auth_email()
          and proposal_draft_id = id
      )
    )
  )
)
with check (
  app.has_role(array['super_admin'::app.app_role])
  or (
    app.has_role(array['admin'::app.app_role])
    and (
      created_by = app.current_profile_id()
      or exists (
        select 1 from app.admin_registry
        where lower(email) = app.auth_email()
          and access_scope = 'all'
          and status != 'inactive'
      )
      or exists (
        select 1 from app.admin_space_access
        where lower(admin_email) = app.auth_email()
          and proposal_draft_id = id
      )
    )
  )
);

-- Grant permissions
grant select, insert, update, delete on app.admin_space_access to service_role;
grant select on app.admin_space_access to authenticated;
grant insert, update, delete on app.admin_space_access to authenticated;

-- Index for performance
create index if not exists idx_admin_space_access_email on app.admin_space_access(admin_email);
create index if not exists idx_admin_space_access_proposal on app.admin_space_access(proposal_draft_id);

-- Proposal supporting documents are optional attachments uploaded during proposal creation.
-- Policies are placed after admin_space_access/auth_email definitions because they reuse
-- the same restricted access model as proposal drafts.
drop policy if exists "proposal_documents_select_parent_access" on app.proposal_documents;
create policy "proposal_documents_select_parent_access"
on app.proposal_documents
for select
using (
  exists (
    select 1
    from app.proposal_drafts d
    where d.id = proposal_draft_id
      and (
        app.has_role(array['super_admin'::app.app_role])
        or d.created_by = app.current_profile_id()
        or exists (
          select 1 from app.admin_registry r
          where lower(r.email) = app.auth_email()
            and r.access_scope = 'all'
            and r.status != 'inactive'
        )
        or exists (
          select 1 from app.admin_space_access a
          where lower(a.admin_email) = app.auth_email()
            and a.proposal_draft_id = d.id
        )
      )
  )
);

drop policy if exists "proposal_documents_insert_owner_or_superadmin" on app.proposal_documents;
create policy "proposal_documents_insert_owner_or_superadmin"
on app.proposal_documents
for insert
with check (
  uploaded_by = app.current_profile_id()
  and exists (
    select 1
    from app.proposal_drafts d
    where d.id = proposal_draft_id
      and (
        app.has_role(array['super_admin'::app.app_role])
        or d.created_by = app.current_profile_id()
        or exists (
          select 1 from app.admin_registry r
          where lower(r.email) = app.auth_email()
            and r.access_scope = 'all'
            and r.status != 'inactive'
        )
        or exists (
          select 1 from app.admin_space_access a
          where lower(a.admin_email) = app.auth_email()
            and a.proposal_draft_id = d.id
        )
      )
  )
);

drop policy if exists "proposal_documents_objects_select_parent_access" on storage.objects;
create policy "proposal_documents_objects_select_parent_access"
on storage.objects
for select
using (
  bucket_id = 'proposal-documents'
  and exists (
    select 1
    from app.proposal_drafts d
    where d.id::text = (storage.foldername(name))[1]
      and (
        app.has_role(array['super_admin'::app.app_role])
        or d.created_by = app.current_profile_id()
        or exists (
          select 1 from app.admin_registry r
          where lower(r.email) = app.auth_email()
            and r.access_scope = 'all'
            and r.status != 'inactive'
        )
        or exists (
          select 1 from app.admin_space_access a
          where lower(a.admin_email) = app.auth_email()
            and a.proposal_draft_id = d.id
        )
      )
  )
);

drop policy if exists "proposal_documents_objects_insert_owner_or_superadmin" on storage.objects;
create policy "proposal_documents_objects_insert_owner_or_superadmin"
on storage.objects
for insert
with check (
  bucket_id = 'proposal-documents'
  and owner = auth.uid()
  and exists (
    select 1
    from app.proposal_drafts d
    where d.id::text = (storage.foldername(name))[1]
      and (
        app.has_role(array['super_admin'::app.app_role])
        or d.created_by = app.current_profile_id()
        or exists (
          select 1 from app.admin_registry r
          where lower(r.email) = app.auth_email()
            and r.access_scope = 'all'
            and r.status != 'inactive'
        )
        or exists (
          select 1 from app.admin_space_access a
          where lower(a.admin_email) = app.auth_email()
            and a.proposal_draft_id = d.id
        )
      )
  )
);

drop policy if exists "public_assets_objects_select_public" on storage.objects;
create policy "public_assets_objects_select_public"
on storage.objects
for select
using (bucket_id = 'public-assets');

drop policy if exists "public_assets_objects_insert_authenticated" on storage.objects;
create policy "public_assets_objects_insert_authenticated"
on storage.objects
for insert
with check (
  bucket_id = 'public-assets'
  and owner = auth.uid()
  and app.has_role(array['admin'::app.app_role, 'super_admin'::app.app_role])
);

-- 2026-06-09 security hardening: proposal-scoped child policies and tx proof integrity.
-- Keep this helper server-side only through RLS; it mirrors proposal_drafts restricted access.
create or replace function app.can_manage_proposal(target_proposal_id uuid)
returns boolean
language sql
stable
security definer
set search_path = app, public
as $$
  select exists (
    select 1
    from app.proposal_drafts d
    where d.id = target_proposal_id
      and (
        app.has_role(array['super_admin'::app.app_role])
        or (
          app.has_role(array['admin'::app.app_role])
          and (
            d.created_by = app.current_profile_id()
            or exists (
              select 1 from app.admin_registry r
              where lower(r.email) = app.auth_email()
                and r.access_scope = 'all'
                and r.status != 'inactive'
            )
            or exists (
              select 1 from app.admin_space_access a
              where lower(a.admin_email) = app.auth_email()
                and a.proposal_draft_id = d.id
            )
          )
        )
      )
  );
$$;

drop policy if exists "proposal_candidates_manage_parent_owner_or_admin" on app.proposal_candidates;
drop policy if exists "proposal_candidates_manage_scoped_admin" on app.proposal_candidates;
create policy "proposal_candidates_manage_scoped_admin"
on app.proposal_candidates
for all
using (app.can_manage_proposal(proposal_draft_id))
with check (app.can_manage_proposal(proposal_draft_id));

drop policy if exists "whitelist_jobs_manage_parent_owner_or_admin" on app.whitelist_import_jobs;
drop policy if exists "whitelist_jobs_manage_scoped_admin" on app.whitelist_import_jobs;
create policy "whitelist_jobs_manage_scoped_admin"
on app.whitelist_import_jobs
for all
using (app.can_manage_proposal(proposal_draft_id))
with check (created_by = app.current_profile_id() and app.can_manage_proposal(proposal_draft_id));

drop policy if exists "whitelist_entries_manage_parent_owner_or_admin" on app.proposal_whitelist_entries;
drop policy if exists "whitelist_entries_manage_scoped_admin" on app.proposal_whitelist_entries;
create policy "whitelist_entries_manage_scoped_admin"
on app.proposal_whitelist_entries
for all
using (app.can_manage_proposal(proposal_draft_id))
with check (app.can_manage_proposal(proposal_draft_id));

drop policy if exists "tx_audit_log_insert_owner_or_admin" on app.tx_audit_log;
drop policy if exists "tx_audit_log_insert_pending_owner_or_admin" on app.tx_audit_log;
create policy "tx_audit_log_insert_pending_owner_or_admin"
on app.tx_audit_log
for insert
with check (
  status = 'pending'
  and source = 'frontend'
  and (
    wallet_address in (
      select wallet_address from app.app_profiles where user_id = auth.uid()
    )
    or app.has_role(array['admin'::app.app_role, 'super_admin'::app.app_role])
  )
);
