// ABI subset dari contracts/src/ElectionSpace.sol
// Digunakan untuk flow frontend (commit/reveal/admin basic actions).
export const EVOTING_ABI = [
  {
    type: 'function',
    name: 'commitVote',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'commitment', type: 'bytes32', internalType: 'bytes32' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'revealVote',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'candidateId', type: 'uint256', internalType: 'uint256' },
      { name: 'salt', type: 'bytes32', internalType: 'bytes32' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'transitionToNextPhase',
    stateMutability: 'nonpayable',
    inputs: [],
    outputs: [],
  },
  {
    type: 'function',
    name: 'registerVoter',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'voter', type: 'address', internalType: 'address' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'unregisterVoter',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'voter', type: 'address', internalType: 'address' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'currentPhase',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint8', internalType: 'enum ElectionSpace.Phase' }],
  },
  {
    type: 'function',
    name: 'status',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint8', internalType: 'enum ElectionSpace.ElectionStatus' }],
  },
  {
    type: 'function',
    name: 'candidateCount',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
  },
  {
    type: 'function',
    name: 'spaceAdmin',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
  },
  {
    type: 'function',
    name: 'registry',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
  },
  {
    type: 'function',
    name: 'isWhitelisted',
    stateMutability: 'view',
    inputs: [{ name: '', type: 'address', internalType: 'address' }],
    outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
  },
  {
    type: 'function',
    name: 'hasCommitted',
    stateMutability: 'view',
    inputs: [{ name: '', type: 'address', internalType: 'address' }],
    outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
  },
  {
    type: 'function',
    name: 'hasRevealed',
    stateMutability: 'view',
    inputs: [{ name: '', type: 'address', internalType: 'address' }],
    outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
  },
  {
    type: 'function',
    name: 'getResult',
    stateMutability: 'view',
    inputs: [{ name: 'candidateId', type: 'uint256', internalType: 'uint256' }],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
  },
  {
    type: 'event',
    name: 'PhaseChanged',
    anonymous: false,
    inputs: [
      { name: 'spaceId', type: 'uint256', indexed: true, internalType: 'uint256' },
      {
        name: 'previousPhase',
        type: 'uint8',
        indexed: true,
        internalType: 'enum ElectionSpace.Phase',
      },
      {
        name: 'newPhase',
        type: 'uint8',
        indexed: true,
        internalType: 'enum ElectionSpace.Phase',
      },
      { name: 'actor', type: 'address', indexed: false, internalType: 'address' },
    ],
  },
  {
    type: 'event',
    name: 'WhitelistUpdated',
    anonymous: false,
    inputs: [
      { name: 'spaceId', type: 'uint256', indexed: true, internalType: 'uint256' },
      { name: 'voter', type: 'address', indexed: true, internalType: 'address' },
      { name: 'isRegistered', type: 'bool', indexed: false, internalType: 'bool' },
      { name: 'actor', type: 'address', indexed: false, internalType: 'address' },
    ],
  },
  {
    type: 'event',
    name: 'Committed',
    anonymous: false,
    inputs: [
      { name: 'spaceId', type: 'uint256', indexed: true, internalType: 'uint256' },
      { name: 'voter', type: 'address', indexed: true, internalType: 'address' },
      { name: 'commitment', type: 'bytes32', indexed: true, internalType: 'bytes32' },
    ],
  },
  {
    type: 'event',
    name: 'Revealed',
    anonymous: false,
    inputs: [
      { name: 'spaceId', type: 'uint256', indexed: true, internalType: 'uint256' },
      { name: 'voter', type: 'address', indexed: true, internalType: 'address' },
      { name: 'candidateId', type: 'uint256', indexed: true, internalType: 'uint256' },
      { name: 'newVoteCount', type: 'uint256', indexed: false, internalType: 'uint256' },
    ],
  },
] as const
